#!/bin/bash

# MIT License

# Copyright (C) 2019, Entynetproject. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

WHO="$( whoami )"
PWD="$( pwd )"
 
      if [[ "$1" = "1" ]]
      then
          PS1="\033[1;31m"$WHO"@ehtools\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m "
      elif [[ "$1" = "2" ]]
      then
          PS1="as system: "
      elif [[ "$1" = "3" ]]
      then
          PS1="\033[34meterm##$:BKUW300PS345672:\033[0m "
      elif [[ "$1" = "4" ]]
      then
          PS1="\033[1;37m[\033[1;31mroot\033[1;37m]:\033[0m "
      elif [[ "$1" = "5" ]]
      then
          PS1="\033[1;31m"$WHO"@kali\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m "
      elif [[ "$1" = "6" ]]
      then
          PS1="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
      elif [[ "$1" = "7" ]]
      then
          PS1="DOS_format: "
      elif [[ "$0" = "8" ]]
      then
          PS1="C:\> "
      elif [[ "$1" = "--list" ]]
      then
      echo -e "\033[1;37m1\033[0m) \033[1;37mehtsh\033[0m"
      echo -e "\033[1;37m2\033[0m) \033[1;37msystem\033[0m"
      echo -e "\033[1;37m3\033[0m) \033[1;37meterm\033[0m"
      echo -e "\033[1;37m4\033[0m) \033[1;37mroot\033[0m"
      echo -e "\033[1;37m5\033[0m) \033[1;37mkali\033[0m"
      echo -e "\033[1;37m6\033[0m) \033[1;37mparrot\033[0m"
      echo -e "\033[1;37m7\033[0m) \033[1;37mDOS_format\033[0m"
      echo -e "\033[1;37m8\033[0m) \033[1;37mC_disk\033[0m"
      fi
