#!/bin/bash

# MIT License

# Copyright (C) 2019, Entynetproject. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

echo -e ""$N"Ehtools Shell - simple ehtools shell."$C""
echo -e ""$N"Copyright (C) 2019 Entynetproject <Ivan Nikolsky>"$C""
  
  if [[ "$1" = "-t" || "$1" = "--theme" ]]
  then
      if [[ "$2" = "-e" || "$2" = "--ehtsh" ]]
      then
      if [[ "$3" = "default" ]]
      then
          THEME="\033[1;31m"$WHO"@ehtools\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$3" = "system" ]]
      then
          THEME="as system:"
      elif [[ "$3" = "eterm" ]]
      then
          THEME="\033[1;34meterm##$:BKUW300PS345672:\033[0m"
      elif [[ "$3" = "root" ]]
      then
          THEME="\033[1;37m[\033[1;31mroot\033[1;37m]:\033[0m"
      elif [[ "$3" = "kali" ]]
      then
          THEME="\033[1;31m"$WHO"@kali\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$3" = "parrot" ]]
      then
          PS1="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
      fi
    if [[ "$2" = "-b" || "$2" = "--bash" ]]
    then
    if [[ "$3" = "default" ]]
      then
          PS1="\033[1;31m"$WHO"@ehtools\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$3" = "system" ]]
      then
          PS1="as system:"
      elif [[ "$3" = "eterm" ]]
      then
          PS1="\033[1;34meterm##$:BKUW300PS345672:\033[0m"
      elif [[ "$3" = "root" ]]
      then
          PS1="\033[1;37m[\033[1;31mroot\033[1;37m]:\033[0m"
      elif [[ "$3" = "kali" ]]
      then
          PS1="\033[1;31m"$WHO"@kali\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$3" = "parrot" ]]
      then
          PS1="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
      fi
    fi
    fi
    while true
    do
        R="\033[1;31m" # Red
        N="\033[1;37m" # White
        G="\033[1;32m" # Green
        O="\033[1;93m" # Orange
        B="\033[1;34m" #Blue
        C="\033[0m" #End
            WHO="$( whoami )"
            PWD="$( pwd )"
printf '\033]2;'$WHO'@ehtools:'$PWD'#\a'
    echo -n -e "$THEME"
    read -p $' ' EXEC

"$EXEC"
 
        if [[ -d /eht ]]
        then    
            {
            echo "$EXEC" >> /eht/.ehtsh_history
            } &> /dev/null
        else
            {
            mkdir /eht
            echo "$EXEC" >> /eht/.ehtsh_history
            } &> /dev/null
        fi
    
    done
