#!/bin/bash

# MIT License

# Copyright (C) 2019, Entynetproject. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

echo -e "\033[1;37mEhtools Shell - simple ehtools shell.\033[0m"
echo -e "\033[1;37mCopyright (C) 2019 Entynetproject <Ivan Nikolsky>\033[0m"
  
WHO="$( whoami )"
PWD="$( pwd )"
  if [[ "$1" = "--theme" ]]
  then
      if [[ "$2" = "ehtsh" ]]
      then
          THEME="\033[1;31m"$WHO"@ehtools\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$2" = "system" ]]
      then
          THEME="as system:"
      elif [[ "$2" = "eterm" ]]
      then
          THEME="\033[34meterm##$:"$WHO":\033[0m"
      elif [[ "$2" = "root" ]]
      then
          THEME="\033[1;37m[\033[1;31mroot\033[1;37m]:\033[0m"
      elif [[ "$2" = "kali" ]]
      then
          THEME="\033[1;31m"$WHO"@kali\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
      elif [[ "$2" = "parrot" ]]
      then
          THEME="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
      elif [[ "$2" = "dos_fat" ]]
      then
          THEME="DOS_fat:"
      elif [[ "$2" = "c_disk" ]]
      then
          THEME="C:\>"
      fi
     
else
THEME="\033[1;31m"$WHO"@ehtools\033[1;37m:\033[1;34m"$PWD"\033[1;37m#\033[0m"
fi
    while true
    do
        R="\033[1;31m" # Red
        N="\033[1;37m" # White
        G="\033[1;32m" # Green
        O="\033[1;93m" # Orange
        B="\033[1;34m" #Blue
        C="\033[0m" #End
            WHO="$( whoami )"
            PWD="$( pwd )"
printf '\033]2;'$WHO'@ehtools:'$PWD'#\a'
    echo -n -e "$THEME"
    read -p $' ' EXEC
$EXEC
        if [[ -d /eht ]]
        then    
            {
            echo "$EXEC" >> /eht/.ehtsh_history
            } &> /dev/null
        else
            {
            mkdir /eht
            echo "$EXEC" >> /eht/.ehtsh_history
            } &> /dev/null
        fi
    
    done
